ViewModels/Admin/ListDeletedItemsViewModel.cs
using System.Collections.Generic;
using Orchard.ContentManagement;

namespace Rijkshuisstijl.VersionManager.ViewModels.Admin
{
    public class ListDeletedItemsViewModel
    {
        public List<ContentItem> RemovedItems { get; set; }
    }
}

ViewModels/Admin/ListViewModel.cs
#region

using Rijkshuisstijl.VersionManager.Models;

#endregion

namespace Rijkshuisstijl.VersionManager.ViewModels.Admin
{
    public class ListViewModel
    {
        public ContentInfoModel ContentInfoModel { get; set; }
    }
}

ViewModels/Admin/SetDescriptionViewModel.cs
#region Usings

using Rijkshuisstijl.VersionManager.InputModels.VersionManager;

#endregion

namespace Rijkshuisstijl.VersionManager.ViewModels.Admin
{
    public class SetDescriptionViewModel
    {
        public SetDescriptionViewModel()
        {}

        public SetDescriptionViewModel(SetDescriptionPostInputModel inputModel)
        {
            Id = inputModel.Id;
            ContentItemId = inputModel.ContentItemId;
            ContentItemVersionId = inputModel.ContentItemVersionId;
            Description = inputModel.Description;
        }

        public int Id { get; set; }
        public int ContentItemId { get; set; }
        public int ContentItemVersionId { get; set; }
        public string Description { get; set; }
    }
}

Controllers/VersionManagerController.cs
#region Usings

using System.Web.Mvc;
using Orchard.Core.Contents;
using Orchard.Localization;
using Orchard.Security;
using Orchard.UI.Admin;
using Rijkshuisstijl.VersionManager.InputModels.VersionManager;
using Rijkshuisstijl.VersionManager.ViewModels.Admin;
using Rijkshuisstijl.VersionManager.WorkerServices;

#endregion

namespace Rijkshuisstijl.VersionManager.Controllers
{
    [Admin]
    public class VersionManagerController : Controller
    {
        private readonly IVersionManagerWorkerService _versionManagerWorkerService;
        private readonly IAuthorizer _authorizer;


        public VersionManagerController(IVersionManagerWorkerService versionManagerWorkerService, IAuthorizer authorizer)
        {
            _versionManagerWorkerService = versionManagerWorkerService;
            _authorizer = authorizer;
            T = NullLocalizer.Instance;
        }


        public Localizer T { get; set; }

        public ActionResult List(int id)
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            ListViewModel viewModel = _versionManagerWorkerService.List(id);
            return View(viewModel);
        }


        public ActionResult Promote(int id, int versionId)
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            _versionManagerWorkerService.Promote(id, versionId);
            return RedirectToAction("List", new {id});
        }


        public ActionResult SetPublishedVersion(int id, int versionId)
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            _versionManagerWorkerService.SetPublishedVersion(id, versionId);
            return RedirectToAction("List", new {id});
        }


        public ActionResult UnsetPublishedVersion(int id, int versionId)
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            _versionManagerWorkerService.UnsetPublishedVersion(id, versionId);
            return RedirectToAction("List", new {id});
        }


        public ActionResult SetDescription(int id, int versionId)
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            SetDescriptionViewModel viewModel = _versionManagerWorkerService.SetDescription(id, versionId);
            return View("SetDescription", viewModel);
        }


        [HttpPost, ActionName("SetDescription")]
        public ActionResult SetDescriptionPost(SetDescriptionPostInputModel inputModel)
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            if (!ModelState.IsValid)
            {
                SetDescriptionViewModel viewModel = new SetDescriptionViewModel(inputModel);
                return View("SetDescription", viewModel);
            }
            _versionManagerWorkerService.SetDescriptionPost(inputModel);
            return RedirectToAction("List", new {id = inputModel.ContentItemId});
        }


        [HttpGet]
        public ActionResult ListDeletedItems()
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            ListDeletedItemsViewModel viewModel = _versionManagerWorkerService.ListDeletedItems();
            return View(viewModel);
        }


        [HttpGet]
        public ActionResult Undelete(int id)
        {
            if (!_authorizer.Authorize(Permissions.EditContent, T("Not authorized to manage versions.")))
            {
                return new HttpUnauthorizedResult();
            }
            _versionManagerWorkerService.Undelete(id);
            return RedirectToAction("ListDeletedItems");
        }
    }
}

Views/VersionManager/List.cshtml
@using Rijkshuisstijl.VersionManager.Models
@model Rijkshuisstijl.VersionManager.ViewModels.Admin.ListViewModel
@{
    string latestTitle = Model.ContentInfoModel.PublishedTitle;
    string latestPermalink = Model.ContentInfoModel.PublishedPermalink;
    Layout.Title = T("Manage versions of {0}", latestTitle);
    Style.Include("versionmanager.css");
}

<div id="versions-list">

    <p>@T("There {0} of this content item.", Model.ContentInfoModel.Versions.Count() == 1 ? "is just one version" : "are " + Model.ContentInfoModel.Versions.Count() + " versions")</p>
    <p> Current permalink : @Model.ContentInfoModel.PublishedPermalink</p>


    <fieldset class="contentItems bulk-items">
        <legend></legend>
        <ul>
            @foreach (ContentVersionInfoModel item in Model.ContentInfoModel.Versions.OrderByDescending(r => r.Version))
            {
                <li>
                    <div class="summary">
                        <div class="primary">
                            <div class="properties">
                                <h3>@T("Version {0}", item.Version)</h3>
                                <div class="metadata">
                                    <ul class="pageStatus">
                                        <li>
                                            @if (item.IsPublished.HasValue && (bool) item.IsPublished)
                                            {
                                                <img class="icon" src="@Href("~/Modules/Rijkshuisstijl.VersionManager/Content/check.gif")" alt="@T("Published version")" title="@T("This is the published versions")" />
                                            }
                                            @if (item.IsPublished.HasValue && !(bool) item.IsPublished)
                                            {
                                                <img class="icon" src="@Href("~/Modules/Rijkshuisstijl.VersionManager/Content/uncheck.gif")" alt="@T("Published version")" title="@T("This is the published versions")" />
                                            }
                                            Published
                                            &nbsp;&#124;&nbsp;
                                        </li>
                                        <li>
                                            @if (item.IsLatest.HasValue && (bool) item.IsLatest)
                                            {
                                                <img class="icon" src="@Href("~/Modules/Rijkshuisstijl.VersionManager/Content/check.gif")" alt="@T("Latest version")" title="@T("This is the published versions")" />
                                            }
                                            @if (item.IsLatest.HasValue && !(bool) item.IsLatest)
                                            {
                                                <img class="icon" src="@Href("~/Modules/Rijkshuisstijl.VersionManager/Content/uncheck.gif")" alt="@T("Latest version")" title="@T("This is the published versions")" />
                                            }
                                            Latest
                                        </li>
                                   
                                    </ul>
                                    @if (String.IsNullOrEmpty(item.Description))
                                    {
                                        @Html.ActionLink(T("no description").Text, "SetDescription", new {id = Model.ContentInfoModel.Id, versionId = item.Id}, new {@class = "description"})
                                    }

                                    else
                                    {
                                        @Html.ActionLink(item.Description, "SetDescription", new {id = Model.ContentInfoModel.Id, versionId = item.Id}, new {@class = "description"})
                                    }
                                   
                                </div>
                            </div>
                            <div class="related">
                                @if (item.IsLatest.HasValue && (bool) item.IsLatest)
                                {
                                    @Html.Link(T("Edit").Text, Url.Action("Edit", "Admin", new {area = "Contents", id = Model.ContentInfoModel.Id, versionId = item.Id}))
                                    <text>&nbsp;&#124;&nbsp;</text>
                                }
                                @if (item.IsPublished.HasValue && (bool) item.IsPublished)
                                {
                                    @Html.Link(T("Unpublish").Text, Url.Action("UnsetPublishedVersion", "VersionManager", new {area = "Rijkshuisstijl.VersionManager", id = Model.ContentInfoModel.Id, versionId = item.Id}))
                                    <text>&nbsp;&#124;&nbsp;</text>
                                }
                                @if (item.IsPublished.HasValue && !(bool) item.IsPublished)
                                {
                                    @Html.Link(T("Publish").Text, Url.Action("SetPublishedVersion", "VersionManager", new {area = "Rijkshuisstijl.VersionManager", id = Model.ContentInfoModel.Id, versionId = item.Id}))
                                    <text>&nbsp;&#124;&nbsp;</text>
                                }
                            
                                @if (item.IsLatest.HasValue && !(bool) item.IsLatest)
                                {
                                    @Html.Link(T("Promote to version {0}", Model.ContentInfoModel.HighestVersion + 1).Text, Url.Action("Promote", "VersionManager", new {area = "Rijkshuisstijl.VersionManager", id = Model.ContentInfoModel.Id, versionId = item.Id}))
                                    <text>&nbsp;&#124;&nbsp;</text>
                                }
                                @Html.Link(T("View").Text, Url.Action("Preview", "Item", new {area = "Contents", id = Model.ContentInfoModel.Id, version = item.Version}))
                            </div>
                        </div>
                        @if (item.Title != latestTitle)
                        {
                            <span class="version-metadata">Titel : '@item.Title'&nbsp;&#124;</span>
                        }
                        @if (item.Permalink != latestPermalink)
                        {
                            <span class="version-metadata">Permalink : @item.Permalink&nbsp;&#124;</span>
                        }
                       

                        <span class="version-metadata">Created : @item.Created&nbsp;&#124;&nbsp;Last modified : @item.Modified&nbsp;&#124;&nbsp;Last published : @item.Published&nbsp;&#124;&nbsp;Version record : @item.Id</span>
                    </div>
                    <a title="View page" href="@Url.Action("Preview", "Item", new {area = "Contents", id = Model.ContentInfoModel.Id, version = item.Version})">
                        <div class="preview">
                            @if (!String.IsNullOrEmpty(@item.Title))
                            {
                                <div class="title-preview">
                                    @item.Title
                                </div>
                            }

                            @if (!String.IsNullOrEmpty(item.IntroFieldText))
                            {
                                <div class="intro-preview">
                                    @if (item.IntroFieldText.Length > 600)
                                    {
                                        <text> @item.IntroFieldText.Substring(0, 600)........</text>
                                    }
                                    else
                                    {
                                        <text> @item.IntroFieldText </text>
                                    }
                                </div>
                            }
                    
                            @if (!String.IsNullOrEmpty(item.BodyText))
                            {
                                <div class="body-preview">
                                    @if (item.BodyText.Length > 900)
                                    {
                                        <text> @item.BodyText.Substring(0, 900)........</text>
                                    }
                                    else
                                    {
                                        <text> @item.BodyText </text>
                                    }
                                </div>
                            }
                        </div> 
                    </a>
                </li>
            }
        </ul>
    </fieldset>
</div>

Views/VersionManager/ListDeletedItems.cshtml
@using System.Text
@using Orchard.Autoroute.Models
@using Orchard.ContentManagement
@using Orchard.Core.Common.Models
@using Orchard.Core.Title.Models
@model Rijkshuisstijl.VersionManager.ViewModels.Admin.ListDeletedItemsViewModel

@{
    Layout.Title = "Recycle Bin";
}

<fieldset class="contentItems">
    <ul>

        @foreach (ContentItem item in Model.RemovedItems)
        {
            <li>

                <div class="summary">
                    @{
                        StringBuilder sb = new StringBuilder();

                        string title = String.Format("Item {0}", item.Id);
                        if (item.Has<TitlePart>() && !String.IsNullOrWhiteSpace(item.As<TitlePart>().Title))
                        {
                            title = item.As<TitlePart>().Title;
                        }
                        sb.AppendFormat("Id : {0}", item.Id);
                        if (item.Has<AutoroutePart>() && !String.IsNullOrWhiteSpace(item.As<AutoroutePart>().Path))
                        {
                            sb.AppendFormat(" | route : {0}", item.As<AutoroutePart>().Path);
                        }
                        if (item.Has<CommonPart>())
                        {
                            sb.AppendFormat(" | owner : {0} | date deleted : {1}", item.As<CommonPart>().Owner.UserName, item.As<CommonPart>().ModifiedUtc);
                        }

                        <h3>@Html.Link(title, Url.Action("Preview", "Item", new { area = "Contents", id = item.Id, version = item.Version })) - @(item.TypeDefinition.DisplayName ?? item.ContentType)</h3>
                        <p>@sb.ToString()</p>
                        <div class="related">
                            @Html.Link(T("Undelete").Text, Url.Action("Undelete", "VersionManager", new {area = "Rijkshuisstijl.VersionManager", id = item.VersionRecord.Id}))
                            &nbsp;&#124;&nbsp;
                            @Html.Link(T("View").Text, Url.Action("Preview", "Item", new {area = "Contents", id = item.Id, version = item.Version}))
                        </div>
                    }
                </div>

            </li>
        }
    </ul>
</fieldset>

Views/VersionManager/SetDescription.cshtml
@model Rijkshuisstijl.VersionManager.ViewModels.Admin.SetDescriptionViewModel
@{
    Layout.Title = T("Edit the description");
}
<div id="version-description">
     
    <div class="errormessages">
        @Html.ValidationSummary()
    </div>

    @using (Html.BeginFormAntiForgeryPost())
    {
        @Html.HiddenFor(m => m.ContentItemId)
        @Html.HiddenFor(m => m.ContentItemVersionId)


        @Html.Label(T("Edit the description").Text, new {@class = "editor-label"})
        @Html.TextBoxFor(m => m.Description, new {@class = "textMedium"})

        <fieldset>
            <legend></legend>
            <button class="primaryAction" type="submit">@T("Save")</button>
        </fieldset>
    }
</div>

@using (Script.Foot())
{
    <script type="text/javascript">
        document.getElementById("VersionManagerRecord_Description").focus();
    </script>
}